/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.demo

import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class AppTests {

    @Test
    fun contextLoads() {
    }

}
