app.auth:
  strategy: JwtFakeHS256
  # issuer: e.g.: https://<your_domain>.eu.auth0.com/
  issuer: https://my-issuer-1.local
  # audience: e.g.: my-audience-1
  audience: my-audience-1
  # the-secret to for symmetric signing
  hs256Secret: "foo - The secret length must be at least 256 bits"
