spring:
  autoconfigure:
    exclude:
      # get rid of "Using default security password" logs and basic auth defaults
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
